
global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'Serasa'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
        - targets: ['localhost:9090']

  - job_name: 'cartesian'
    scrape_interval: 5s
    static_configs:
      - targets: ['cartesian:2112']
  