name: Docker Compose

on:
  push: {}
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Source env
         run: source .env.example

      - name: Build Docker Image
        run: docker-compose build
