name: Terraform

on:
  push: {}
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform init
      run: terraform init terraform/

    - name: Terraform plan
      run: terraform plan terraform/ -no-color

    - run: echo ${{ steps.plan.outputs.stdout }}
    - run: echo ${{ steps.plan.outputs.stderr }}
    - run: echo ${{ steps.plan.outputs.exitcode }}
