name: Terraform

on:
  push: {}
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Terraform fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform plan
      run: terraform plan  -no-color
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
